[package]
name = "corona"
# Also increase the version in src/lib html root attribute
# TODO: Bump to 0.4, since there's a back-incompatible change in the API
version = "0.3.1"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Coroutine and Async/Await support for tokio-based futures"
documentation = "https://docs.rs/corona"
repository = "https://github.com/vorner/corona"
readme = "README.md"
keywords = ["coroutine", "future", "tokio", "await"]
categories = ["asynchronous"]
license = "Apache-2.0/MIT"

[badges]
travis-ci = { repository = "vorner/corona" }
appveyor = { repository = "vorner/corona" }
maintenance = { status = "actively-developed" }

[dependencies]
context = "~2"
futures = "~0.1"
tokio-core = "~0.1"

[dev-dependencies]
tokio-io = "~0.1"
bytes = "~0.4"
version-sync = "~0.5"
